name: orthogather
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - flask
  - flask-session
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - upsetplot
  - goatools
  - requests
  - openpyxl
  - orthofinder=2.5.5
